---
title: "Getting_Cleaning_Week1"
author: "Shubham Gupta"
date: "December 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```


```{r downloadFile, cache=TRUE}
setwd("C://Users//shubh//Google Drive//Athletigen Work learning")
if(!file.exists("data")){
dir.create("data")
}
# https://data.baltimorecity.gov/api/views/dz54-2aru
fileURL <- "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.csv?accessType=DOWNLOAD"
download.file(fileURL, destfile = "./data/camera.csv", method = "curl") # Curl method is for https
list.files("./data")
dateDownloaded <- date()
dateDownloaded
```

#Read flat files
```{r}
# Most common as it is more robust
cameraData <- read.table("./data/camera.csv", sep=",", header = TRUE) # default sep is tab delimited file
head(cameraData)
# other params to be specified are "quote", "na.string", "nrows", "skip"
```

# Read excel
```{r}
if(!file.exists("data")){dir.create("data")}
fileURL <- "https://data.baltimorecity.gov/api/views/dz54-2aru/rows.xlsx?accessType=DOWNLOAD"
download.file(fileURL, destfile = "./data/cameras.xlsx", method = "curl") # download.file is agnostic to file type
dateDownloaded <- date()
list.files("./data")
```


```{r}
library(xlsx)
#cameraData <- read.xlsx("./data/cameras.xlsx", sheetIndex = 1, header = TRUE) #link is broken, you can specify subset of rows and columns.
head(cameraData)
```

### Data table
```{r}
library(data.table)
DF = data.frame(x = rnorm(9), y = rep(c("a","b","c"), each =3),z = rnorm(9))
head(DF, n = 3)
DT = data.table(x = rnorm(9),  y = rep(c("a","b","c"), each =3),z = rnorm(9))
head(DT, 3)
tables()
DT[2,]
DT[DT$y == 'a',]
DT[c(2,3)]
DT[,c(2,3)] # Wierd
DT[, list(mean(x), sum(z))]
DT[,w:=z^2] # Efficient over data frame as 2 copies of data frame in memory, but with data table this is not the way
DT2 <- DT # use copy function instead
DT[, y:=2]
head(DT, 3)
head(DT2, 3)
DT[, m:={tmp<-(x+z); log2(tmp+5)}]
DT
DT[, a:= x>0]
DT
DT[, b := mean(x+w), by = a]
DT
```



## Session Info
```{r Session_Info, comment = NA}
devtools::session_info()
```

## Last compilation
Last compiled at `r Sys.Date()`.